### ISSUE TITLE
Lists show 0/4 but if there's an invalid ID it don't show the level.

### ISSUE THREAD

**Issue by xendyex** [SevenworksDev/GD-2.2-Lists#1]
Um so basically I made a list on my alt and tried to see what happened if I put ID 1 (for Stereo Madness) and I also put 2. Now it says 0/4 on the menu ( I cant be bothered to complete any ) but then there's only 2 levels. Yeah uh I don't think this is intended. Good idea: let it show stereo madness etc

**Comment by SevenworksDev** [comment]
Geometry Dash only will show IDs that belong to custom levels and not any other IDs. Its impossible to show Stereo Madness or anything else without having to implement something for C++ too which I am not too good at. Added level checking to my TODO.md list
